document.open();
document.write("<div class='header'>");
document.write("<div class='logo'>");
document.write("<a href='index.html'><img src='Images/Viajes auricular.png' alt='Viajes Auricular' width='50px' style='border-radius: 10px;'></a>");
document.write("<h1 class='nombreLogo'>Viajes Auricular</h1>");
document.write("</div>");
document.write("<div class='Registro'>");
document.write("<div class='contacto'>");
document.write("        <img src='Images/telefono.PNG' alt='telefono' height='35px'>");
document.write("        <p>0800-AURI-1234</p>");
document.write("    </div>");
document.write("    <div class='inicio'>");
document.write("        <img src='Images/inicio.png' alt='' height='35px'>");
document.write("        <p> <a href='iniciarsesion.html'>INICIAR SESIÓN</a></p>");
document.write("    </div> ");
document.write("</div>");
document.write("</div>");
document.write("<div class='botonav navbar'>");
document.write("<div class='buscaTuVuelo'>Busca tu vuelo</div>");
document.write("<div class='promociones'>Promociones</div>");
document.write("<div class='clubAuri'>Club Auri</div>");
document.write("<div class='actividades'>Actividades</div>");
document.write("</div>");
document.close();